name: pinch_zoom_image_last
description: Pinch Zoom Image package last fixed version. The owner of this package is not accept the pull request. That so I created updated version and you can open issues. I can fix asap.
version: 0.3.2
homepage: https://github.com/furkankurt/pinch_zoom_image_last

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: tr.com.furkankurt.pinch_zoom_image.pinch_zoom_image_last
    pluginClass: PinchZoomImageLastPlugin
